project_id = "nkqwhiqrljwvzrivhqyh"

[functions.omniva-create-shipment]
verify_jwt = false

[functions.omniva-label-pdf]
verify_jwt = false

[functions.omniva-tracking-sync]
verify_jwt = false

[functions.send-tracking-email]
verify_jwt = false

[functions.omniva-locations]
verify_jwt = false

[functions.zakeke-products]
verify_jwt = false

[functions.zakeke-token]
verify_jwt = false

[functions.montonio-webhook]
verify_jwt = false

[functions.montonio-shipping-methods]
verify_jwt = false

[functions.montonio-create-order]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-order-cancelled]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.send-contact-reply]
verify_jwt = false
